[features]
seeds = false
[programs.localnet]
staking = "5E1FrMGJa9S1qJHXVZKdhuu3WF8BrwzNdx1JKARyNbVm"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/leonidkornev/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
